image: maven:3.9.6-eclipse-temurin-21


variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
  - test
  - package
  - tools

cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - .m2/repository

test:unit:
  stage: test
  script:
    - mvn clean verify
  artifacts:
    when: always
    paths:
      - target/site/jacoco
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml
  rules:
    - when: always

build:jar:
  stage: package
  script:
    - mvn -DskipTests package
  artifacts:
    paths:
      - target/*.jar
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

pages:
  image: alpine:latest
  stage: package
  script:
    - mv target/site/jacoco public
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

tools:generate-pdf:
  image: ubuntu:20.04
  stage: tools
  script:
    - apt-get update
    - apt-get install -y wget fontconfig libfreetype6 libjpeg-turbo8 libpng16-16 libx11-6 libxcb1 libxext6 libxrender1 xfonts-75dpi xfonts-base git nodejs npm
    - wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.focal_amd64.deb
    - dpkg -i wkhtmltox_0.12.6-1.focal_amd64.deb
    - npm install -g github-wikito-converter
    - export my_url="${CI_PROJECT_URL:8}"
    - export final_url="https://gitlab-ci-token:$CI_JOB_TOKEN@$my_url"
    - git clone "$final_url.wiki.git"
    - gwtc "$CI_PROJECT_TITLE.wiki" || gwtc <your-manual-wiki-repo-name>
    - wkhtmltopdf documentation.html wiki.pdf
  artifacts:
    paths:
      - wiki.pdf
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
