name: CI Pipeline

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main, dev" ]
  workflow_dispatch:

env:
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=.m2/repository
    -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true
  SPRING_PROFILES_ACTIVE: gitlab-ci

jobs:

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ensure .m2 directory exists
        run: mkdir -p ~/.m2/repository

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run tests with coverage
        run: mvn clean verify

      - name: Upload JaCoCo coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco

      - name: Upload JUnit test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-results
          path: |
            target/surefire-reports/TEST-*.xml
            target/failsafe-reports/TEST-*.xml

  package:
    name: Build Jar
    runs-on: ubuntu-latest
    needs: test
#    if: github.ref_name == 'dev'
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build application jar
        run: mvn -DskipTests package

      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: application-jar
          path: target/*.jar

  pages:
    name: Publish Coverage as Artifact
    runs-on: ubuntu-latest
    needs: test
#    if: github.ref_name == 'dev'
    steps:
      - uses: actions/checkout@v4

      - name: Download JaCoCo report
        uses: actions/download-artifact@v4
        with:
          name: jacoco-report
          path: jacoco

      - name: Move report to public dir
        run: mkdir -p public && mv jacoco/* public/

      - name: Upload public directory
        uses: actions/upload-artifact@v4
        with:
          name: public
          path: public/

#  generate-pdf:
#    name: Generate Wiki PDF
#    runs-on: ubuntu-latest
#    if: github.event_name == 'workflow_dispatch'
#    steps:
#      - name: Install dependencies
#        run: |
#          sudo apt-get update
#          sudo apt-get install -y wget fontconfig libfreetype6 libjpeg-turbo8 libpng16-16 libx11-6 libxcb1 libxext6 libxrender1 xfonts-75dpi xfonts-base git nodejs npm
#
#      - name: Install wkhtmltopdf
#        run: |
#          wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.focal_amd64.deb
#          sudo dpkg -i wkhtmltox_0.12.6-1.focal_amd64.deb
#
#      - name: Install github-wikito-converter
#        run: sudo npm install -g github-wikito-converter
#
#      - name: Clone wiki
#        run: |
#          REPO_URL="https://github.com/${{ github.repository }}.wiki.git"
#          git clone $REPO_URL wiki
#
#      - name: Generate HTML and PDF
#        run: |
#          cd wiki
#          gwtc "$(basename ${{ github.repository }})"
#          wkhtmltopdf documentation.html ../wiki.pdf
#
#      - name: Upload PDF
#        uses: actions/upload-artifact@v4
#        with:
#          name: wiki-pdf
#          path: wiki.pdf
